services:
  server:
    build:
      context: Dockerfile
      target: dev
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    links:
      - mongodb
      - smtp-server
    environment:
      MONGO_URI: mongodb
      SERVER_KEK: ${SERVER_KEK}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MAIL_NAME: ${MAIL_NAME}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_PORT: ${SMTP_PORT}
      X_API_KEY: ${X_API_KEY}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./src:/app/src

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/mongodb
    command: mongod --quiet --logpath /dev/null 

  smtp-server:
    build:
      context: ./smtp
      target: smtp
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    ports:
      - 25:25

